document.write("<div class='wienx'>")
document.write("<img src='/nbggxyww/resources/images/weixin.png'>")
document.write("</div>")
document.write("<li><a href='http://www.nbcredit.gov.cn'>首页</a></li>")
document.write("<li><a href='http://www.nbcredit.gov.cn/col/col10/index.html'>信用动态</a></li>")
document.write("<li><a href='http://www.nbcredit.gov.cn/col/col14/index.html'>政策法规</a></li>")
document.write("<li><a href='http://www.nbcredit.gov.cn/col/col232/index.html'>联合奖惩</a></li>")
document.write("<li><a href='http://www.nbcredit.gov.cn/col/col8/index.html'>信用研究</a></li>") 
document.write("<li><a href='http://www.nbcredit.gov.cn/col/col230/index.html'>信用宣传</a></li>")
document.write("<li><a href='http://www.nbcredit.gov.cn/col/col246/index.html'>办事指南</a></li>")
